# Generated by Django 3.2.8 on 2022-04-14 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslots',
            name='branch',
        ),
        migrations.DeleteModel(
            name='SlotDomain',
        ),
        migrations.DeleteModel(
            name='TimeSlots',
        ),
    ]
