# Generated by Django 3.2.8 on 2022-04-14 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_auto_20220414_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='departments.branch'),
        ),
        migrations.DeleteModel(
            name='WorkingDays',
        ),
    ]
